// Список доступных иконок для выбора в категориях
export const AVAILABLE_ICONS = [
  "Utensils", "Car", "Film", "Hospital", "Shirt", "Home", "Wallet", "Package",
  "Pizza", "Coffee", "Beer", "Gamepad2", "Smartphone", "Laptop", "Plane", "Umbrella",
  "GraduationCap", "Pill", "Gift", "CreditCard", "Dumbbell", "Palette", "BookOpen", "Music",
  "Cake", "Salad", "Wine", "Bus", "Train", "Bike", "Fuel", "ShoppingCart",
  "Lipstick", "Bottle", "Broom", "Wrench", "Lightbulb", "Thermometer", "Tv", "Plug",
  "Briefcase", "BarChart3", "TrendingUp", "DollarSign", "Yen", "Euro", "PoundSterling", "Coins",
  "Heart", "Star", "Tag", "Bookmark", "Bell", "Calendar", "Clock", "Settings",
  "User", "Users", "Mail", "Phone", "MessageSquare", "Camera", "Image", "File",
  "Folder", "Download", "Upload", "Share", "Edit", "Trash2", "Plus", "Minus",
  "Check", "X", "ArrowRight", "ArrowLeft", "ArrowUp", "ArrowDown", "Search", "Filter"
];

// Маппинг старых эмодзи на новые имена иконок (для миграции)
export const EMOJI_TO_ICON: Record<string, string> = {
  "🍔": "Utensils",
  "🚗": "Car",
  "🎬": "Film",
  "🏥": "Hospital",
  "👕": "Shirt",
  "🏠": "Home",
  "💰": "Wallet",
  "📦": "Package",
  "🍕": "Pizza",
  "☕": "Coffee",
  "🍺": "Beer",
  "🎮": "Gamepad2",
  "📱": "Smartphone",
  "💻": "Laptop",
  "✈️": "Plane",
  "🏖️": "Umbrella",
  "🎓": "GraduationCap",
  "💊": "Pill",
  "🎁": "Gift",
  "💳": "CreditCard",
  "🏋️": "Dumbbell",
  "🎨": "Palette",
  "📚": "BookOpen",
  "🎵": "Music",
  "🍰": "Cake",
  "🥗": "Salad",
  "🍷": "Wine",
  "🚌": "Bus",
  "🚇": "Train",
  "🚲": "Bike",
  "⛽": "Fuel",
  "🛒": "ShoppingCart",
  "💄": "Lipstick",
  "🧴": "Bottle",
  "🧹": "Broom",
  "🔧": "Wrench",
  "💡": "Lightbulb",
  "🌡️": "Thermometer",
  "📺": "Tv",
  "🔌": "Plug",
  "💼": "Briefcase",
  "📊": "BarChart3",
  "📈": "TrendingUp",
  "💵": "DollarSign",
  "💴": "Yen",
  "💶": "Euro",
  "💷": "PoundSterling",
  "💸": "Coins",
};
